/*
VP-CBP compatibility patch!
0 = Disabled disregarding if its detects VP-CBP by many.
1 = Enabled if it detects the VP-CBP by many.
2 = Disabled until it detects something! (Default)
*/

INSERT INTO COMMUNITY	
		(Type,			Value)
VALUES	('ACN-VP-CBP', 	2);

UPDATE COMMUNITY
SET Value = '1'
WHERE Type = 'ACN-VP-CBP' AND EXISTS (SELECT * FROM Units WHERE Type='UNIT_COLONIST') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=0);

/*
MUCfVP compatibility patch!
0 = Disabled disregarding if its detects MUCfVP by many.
1 = Enabled if it detects the MUCfVP by many.
2 = Disabled until it detects something! (Default)
*/

INSERT INTO COMMUNITY	
		(Type,			Value)
VALUES	('ACN-MUCfVP', 	2);

UPDATE COMMUNITY
SET Value = '1'
WHERE Type = 'ACN-MUCfVP' AND EXISTS (SELECT * FROM Units WHERE Type='UNIT_ZULU_INDABA') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=0);

/*
Compatibility patch for additional civilizations!
0 = Disabled disregarding if its detects Civilization.
1 = Enabled if it detects the Civilization.
2 = Disabled until it detects something! (Default)
*/

INSERT INTO COMMUNITY	
		(Type,			Value)
VALUES	('ACN-CIV-ISR', 2);

UPDATE COMMUNITY
SET Value = '1'
WHERE Type = 'ACN-CIV-ISR' AND EXISTS (SELECT * FROM Units WHERE Type='UNIT_ISRAEL_SHOPHET') AND NOT EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-CIV-ISR' AND Value=0);
--==============================================================================================================================================================================================================================================================================================--
--==============================================================================================================================================================================================================================================================================================--
-- Alternative Names
	-- Xenonyms
		-- VP
		UPDATE Language_en_US SET Text = 'Fighting Elephant' WHERE Tag = 'TXT_KEY_UNIT_INDIAN_WARELEPHANT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=1 OR Value=2)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Yurt' WHERE Tag = 'TXT_KEY_BUILDING_YURT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=1 OR Value=2)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
			-- detailed VP
			UPDATE Language_en_US SET Text = 'Pike and Shot' WHERE Tag = 'TXT_KEY_UNIT_SPANISH_TERCIO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND Value=2) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
			UPDATE Language_en_US SET Text = 'Spear Thrower' WHERE Tag = 'TXT_KEY_UNIT_MAYAN_ATLATLIST' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND Value=2) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		-- MUCfVP
		UPDATE Language_en_US SET Text = 'Shotel Swordsman' WHERE Tag = 'TXT_KEY_UNIT_ETHIOPIA_SHOTELAI' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=1 OR Value=2)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Armstrong Gun' WHERE Tag = 'TXT_KEY_UNIT_SIAM_SEIR_MORB' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=1 OR Value=2)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Sauna' WHERE Tag = 'TXT_KEY_BUILDING_SWEDEN_BASTU' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=1 OR Value=2)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Lagoon' WHERE Tag = 'TXT_KEY_BUILDING_VENICE_LAGUNA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=1 OR Value=2)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Galiot' WHERE Tag = 'TXT_KEY_UNIT_VENICE_FUSTA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=1 OR Value=2)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Mughal Fort' WHERE Tag = 'TXT_KEY_BUILDING_INDIA_QILA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=1 OR Value=2)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Paradise Garden' WHERE Tag = 'TXT_KEY_BUILDING_PERSIA_PAIRIDAEZA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=1 OR Value=2)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Mailed Companion' WHERE Tag = 'TXT_KEY_UNIT_POLAND_PANCERNY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=1 OR Value=2)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Danish Cooperative Movement' WHERE Tag = 'TXT_KEY_BUILDING_DENMARK_ANDELSBEVAEGELSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=1 OR Value=2)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
			-- detailed MUCfVP
			
	-- Endonyms
		-- VP
		UPDATE Language_en_US SET Text = 'Ghazi' WHERE Tag = 'TXT_KEY_UNIT_ARABIAN_CAMELARCHER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Kaffeehaus' WHERE Tag = 'TXT_KEY_BUILDING_COFFEE_HOUSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Ocelotl' WHERE Tag = 'TXT_KEY_UNIT_AZTEC_JAGUAR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Chinampa' WHERE Tag = 'TXT_KEY_BUILDING_FLOATING_GARDENS_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Qashtum' WHERE Tag = 'TXT_KEY_UNIT_BABYLON_BOWMAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Campo do Pernambuco' WHERE Tag = 'TXT_KEY_IMPROVEMENT_BRAZILWOOD_CAMP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Curadh' WHERE Tag = 'TXT_KEY_UNIT_CELT_PICTISH_WARRIOR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Lian Nu' WHERE Tag = 'TXT_KEY_UNIT_CHINESE_CHUKONU' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Watergeuzen' WHERE Tag = 'TXT_KEY_UNIT_SEA_BEGGAR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Hawelti' WHERE Tag = 'TXT_KEY_BUILDING_STELE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Huaraca' WHERE Tag = 'TXT_KEY_UNIT_INCAN_SLINGER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Anden' WHERE Tag = 'TXT_KEY_IMPROVEMENT_TERRACE_FARM' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Vaav' WHERE Tag = 'TXT_KEY_BUILDING_INDUS_CANAL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Catabhata' WHERE Tag = 'TXT_KEY_UNIT_INDONESIAN_KRIS_SWORDSMAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Haudenosesne' WHERE Tag = 'TXT_KEY_BUILDING_LONGHOUSE_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Rotisken''rakehte' WHERE Tag = 'TXT_KEY_UNIT_IROQUOIAN_MOHAWKWARRIOR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Haan' WHERE Tag = 'TXT_KEY_UNIT_MONGOL_KHAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Goumiers' WHERE Tag = 'TXT_KEY_UNIT_BERBER_CAVALRY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Tophane-i Amire' WHERE Tag = 'TXT_KEY_BUILDING_SIEGE_WORKSHOP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Stajnia Ksiazeca' WHERE Tag = 'TXT_KEY_BUILDING_DUCAL_STABLE_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Husaria' WHERE Tag = 'TXT_KEY_UNIT_POLISH_WINGED_HUSSAR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Ika a Whiro' WHERE Tag = 'TXT_KEY_UNIT_POLYNESIAN_MAORI_WARRIOR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Pungkuto''ettu' WHERE Tag = 'TXT_KEY_UNIT_SHOSHONE_COMANCHE_RIDERS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Katukkatun' WHERE Tag = 'TXT_KEY_IMPROVEMENT_ENCAMPMENT_SHOSHONE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Chang Suek' WHERE Tag = 'TXT_KEY_UNIT_SIAMESE_WARELEPHANT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Farari' WHERE Tag = 'TXT_KEY_UNIT_SONGHAI_MUSLIMCAVALRY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Magni Mercante' WHERE Tag = 'TXT_KEY_UNIT_VENETIAN_MERCHANT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Zao Zhi' WHERE Tag = 'TXT_KEY_BUILDING_PAPER_MAKER_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
			-- detailed VP
			UPDATE Language_en_US SET Text = 'Qasbah' WHERE Tag = 'TXT_KEY_IMPROVEMENT_KASBAH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND Value=4) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
			UPDATE Language_en_US SET Text = 'Oplitis' WHERE Tag = 'TXT_KEY_UNIT_GREEK_HOPLITE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND Value=4) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
			UPDATE Language_en_US SET Text = 'Cataphractos' WHERE Tag = 'TXT_KEY_UNIT_BYZANTINE_CATAPHRACT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND Value=4) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
			UPDATE Language_en_US SET Text = 'Yeniceri' WHERE Tag = 'TXT_KEY_UNIT_OTTOMAN_JANISSARY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND Value=4) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
			UPDATE Language_en_US SET Text = 'Mousquetaire' WHERE Tag = 'TXT_KEY_UNIT_FRENCH_MUSKETEER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND Value=4) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
			UPDATE Language_en_US SET Text = 'Husar' WHERE Tag = 'TXT_KEY_UNIT_AUSTRIAN_HUSSAR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND Value=4) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
			UPDATE Language_en_US SET Text = 'Mision' WHERE Tag = 'TXT_KEY_BUILDING_MISSION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND Value=4) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-VP-CBP' AND Value=1);
		-- MUCfVP
		UPDATE Language_en_US SET Text = 'Al-Hashimiyun' WHERE Tag = 'TXT_KEY_UNIT_ARABIA_HASHEMITE_RAIDER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Cuauhtli' WHERE Tag = 'TXT_KEY_UNIT_AZTEC_EAGLE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Covinni' WHERE Tag = 'TXT_KEY_UNIT_CELTS_SCYTHED_CHARIOT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Dunon' WHERE Tag = 'TXT_KEY_IMPROVEMENT_CELTS_OPPIDUM' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Kao-Chang' WHERE Tag = 'TXT_KEY_BUILDING_CHINA_EXAMINATION_HALL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Langskib' WHERE Tag = 'TXT_KEY_UNIT_DENMARK_LANGSKIB' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Deutscher Orden' WHERE Tag = 'TXT_KEY_BUILDING_GERMANY_TEUTONIC_ORDER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Alti Cur' WHERE Tag = 'TXT_KEY_BUILDING_HUNS_ALTI_CUR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Ne Hatoraz' WHERE Tag = 'TXT_KEY_UNIT_IROQUOIS_PROWLER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Kobukseon' WHERE Tag = 'TXT_KEY_CIV5_KOREA_TURTLESHIP_HEADING' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Pitz Court' WHERE Tag = 'TXT_KEY_BUILDING_MAYA_PITZ' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Alqirsan' WHERE Tag = 'TXT_KEY_UNIT_MOROCCO_CORSAIR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Sahi Topu' WHERE Tag = 'TXT_KEY_UNIT_OTTOMANS_GREAT_TURKISH_BOMBARD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Yedinorog' WHERE Tag = 'TXT_KEY_UNIT_RUSSIA_LICORNE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Ohamupe' WHERE Tag = 'TXT_KEY_UNIT_SHOSHONE_YELLOW_BROW' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Pis''kun' WHERE Tag = 'TXT_KEY_BUILDING_SHOSHONE_BUFFALO_POUND' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
		UPDATE Language_en_US SET Text = 'Baan Chang' WHERE Tag = 'TXT_KEY_BUILDING_SIAM_BAAN_CHANG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND (Value=3 OR Value=4)) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
			-- detailed MUCfVP
			UPDATE Language_en_US SET Text = 'Kleftis' WHERE Tag = 'TXT_KEY_UNIT_GREECE_KLEPHT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND Value=4) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
			UPDATE Language_en_US SET Text = 'Barbakan' WHERE Tag = 'TXT_KEY_BUILDING_POLAND_BARBICAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND Value=4) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
			UPDATE Language_en_US SET Text = 'Towarzysz Pancerny' WHERE Tag = 'TXT_KEY_UNIT_POLAND_PANCERNY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND Value=4) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
			UPDATE Language_en_US SET Text = 'Hippodromos' WHERE Tag = 'TXT_KEY_BUILDING_BYZANTIUM_HIPPODROME' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND Value=4) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
			UPDATE Language_en_US SET Text = 'Khepesh' WHERE Tag = 'TXT_KEY_UNIT_EGYPT_KHOPESH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND Value=4) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
			UPDATE Language_en_US SET Text = 'Kabuki' WHERE Tag = 'TXT_KEY_BUILDING_JAPAN_KABUKI' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND Value=4) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);
			UPDATE Language_en_US SET Text = 'Universidade de Coimbra' WHERE Tag = 'BUILDING_PORTUGAL_UNIVERSITY_OF_COIMBRA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNALT' AND Value=4) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACN-MUCfVP' AND Value=1);	
--==============================================================================================================================================================================================================================================================================================--
--==============================================================================================================================================================================================================================================================================================--
-- Civilization Names
	-- Endoetnonyms
		-- VP
		UPDATE Language_en_US SET Text = 'America' WHERE Tag = 'TXT_KEY_CIV_AMERICA_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'United States of America' WHERE Tag = 'TXT_KEY_CIV_AMERICA_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Arabiya' WHERE Tag = 'TXT_KEY_CIV_ARABIA_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Al-khilafatu al-''abbasiyyah' WHERE Tag = 'TXT_KEY_CIV_ARABIA_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Athura' WHERE Tag = 'TXT_KEY_CIV_ASSYRIA_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Athura' WHERE Tag = 'TXT_KEY_CIV_ASSYRIA_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Habsburgermonarchie' WHERE Tag = 'TXT_KEY_CIV_AUSTRIA_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Habsburgische-Osterreichische Erblande' WHERE Tag = 'TXT_KEY_CIV_AUSTRIA_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Mexica' WHERE Tag = 'TXT_KEY_CIV_AZTEC_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Mexica' WHERE Tag = 'TXT_KEY_CIV_AZTEC_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Babylon' WHERE Tag = 'TXT_KEY_CIV_FRANCE_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Babylon' WHERE Tag = 'TXT_KEY_CIV_FRANCE_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Brasil' WHERE Tag = 'TXT_KEY_CIV_BRAZIL_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Imperio do Brasil' WHERE Tag = 'TXT_KEY_CIV_BRAZIL_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Romaioi' WHERE Tag = 'TXT_KEY_CIV_BYZANTIUM_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = ' Imperium Romanum Orientale' WHERE Tag = 'TXT_KEY_CIV_BYZANTIUM_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Iceni' WHERE Tag = 'TXT_KEY_CIV_CELTS_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Iceni' WHERE Tag = 'TXT_KEY_CIV_CELTS_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Qart-hadasht' WHERE Tag = 'TXT_KEY_CIV_CARTHAGE_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Qart-hadasht' WHERE Tag = 'TXT_KEY_CIV_CARTHAGE_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Zhongguo' WHERE Tag = 'TXT_KEY_CIV_CHINA_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Zhongguo' WHERE Tag = 'TXT_KEY_CIV_CHINA_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Danmark' WHERE Tag = 'TXT_KEY_CIV_DENMARK_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Kongeriget Danmark' WHERE Tag = 'TXT_KEY_CIV_DENMARK_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Khemi' WHERE Tag = 'TXT_KEY_CIV_EGYPT_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Rem en Khemi' WHERE Tag = 'TXT_KEY_CIV_EGYPT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'England' WHERE Tag = 'TXT_KEY_CIV_PORTUGAL_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Kingdom of England' WHERE Tag = 'TXT_KEY_CIV_PORTUGAL_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Ityoppya' WHERE Tag = 'TXT_KEY_CIV_ETHIOPIA_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'ye''Itiyoppya Federalawi Demokirasiyawi Ripebilik' WHERE Tag = 'TXT_KEY_CIV_ETHIOPIA_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'France' WHERE Tag = 'TXT_KEY_CIV_FRANCE_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Empire Francais' WHERE Tag = 'TXT_KEY_CIV_FRANCE_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Deutschland' WHERE Tag = 'TXT_KEY_CIV_GERMANY_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Deutsches Kaiserreich' WHERE Tag = 'TXT_KEY_CIV_GERMANY_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Hun' WHERE Tag = 'TXT_KEY_CIV_HUNS_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Hun' WHERE Tag = 'TXT_KEY_CIV_HUNS_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Tawantinsuyu' WHERE Tag = 'TXT_KEY_CIV_INCA_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Tawantinsuyu' WHERE Tag = 'TXT_KEY_CIV_INCA_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Bharat' WHERE Tag = 'TXT_KEY_CIV_INDIA_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Bharat Ganarajya' WHERE Tag = 'TXT_KEY_CIV_INDIA_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Majapahit' WHERE Tag = 'TXT_KEY_CIV_PORTUGAL_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Karaton Majapahit' WHERE Tag = 'TXT_KEY_CIV_PORTUGAL_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Haudenosaunee' WHERE Tag = 'TXT_KEY_CIV_IROQUOIS_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Haudenosaunee' WHERE Tag = 'TXT_KEY_CIV_IROQUOIS_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Nippon' WHERE Tag = 'TXT_KEY_CIV_JAPAN_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Nippon-koku' WHERE Tag = 'TXT_KEY_CIV_JAPAN_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Joseon' WHERE Tag = 'TXT_KEY_CIV_KOREA_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Joseon' WHERE Tag = 'TXT_KEY_CIV_KOREA_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Maya' WHERE Tag = 'TXT_KEY_CIV_MAYA_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Maya' WHERE Tag = 'TXT_KEY_CIV_MAYA_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Monggol Ulus' WHERE Tag = 'TXT_KEY_CIV_MONGOL_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Monggol Ulus' WHERE Tag = 'TXT_KEY_CIV_MONGOL_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Al-magrib' WHERE Tag = 'TXT_KEY_CIV_MOROCCO_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Al-mamlakah al-maghribiyah' WHERE Tag = 'TXT_KEY_CIV_MOROCCO_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Verenigde Provincien' WHERE Tag = 'TXT_KEY_CIV_NETHERLANDS_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Republiek der Zeven Verenigde Nederlanden' WHERE Tag = 'TXT_KEY_CIV_NETHERLANDS_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Osmanli Türkleri' WHERE Tag = 'TXT_KEY_CIV_OTTOMAN_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Devlet-i Aliye-i Osmaniye' WHERE Tag = 'TXT_KEY_CIV_OTTOMAN_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Xshassa' WHERE Tag = 'TXT_KEY_CIV_PERSIA_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Haxamanishiya' WHERE Tag = 'TXT_KEY_CIV_PERSIA_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Polska' WHERE Tag = 'TXT_KEY_CIV_POLAND_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Krolestwo Polskie' WHERE Tag = 'TXT_KEY_CIV_POLAND_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Portugal' WHERE Tag = 'TXT_KEY_CIV_PORTUGAL_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Reino de Portugal' WHERE Tag = 'TXT_KEY_CIV_PORTUGAL_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Roma' WHERE Tag = 'TXT_KEY_CIV_ROME_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Imperium Romanum' WHERE Tag = 'TXT_KEY_CIV_ROME_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Rossiya' WHERE Tag = 'TXT_KEY_CIV_RUSSIA_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Rossiyskaya Imperiya' WHERE Tag = 'TXT_KEY_CIV_RUSSIA_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Newe' WHERE Tag = 'TXT_KEY_CIV_SHOSHONE_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Newe' WHERE Tag = 'TXT_KEY_CIV_SHOSHONE_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Sukhotai' WHERE Tag = 'TXT_KEY_CIV_SIAM_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Xanacakr Sukhothai' WHERE Tag = 'TXT_KEY_CIV_SIAM_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Songhai' WHERE Tag = 'TXT_KEY_CIV_SONGHAI_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Songhai' WHERE Tag = 'TXT_KEY_CIV_SONGHAI_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Espana' WHERE Tag = 'TXT_KEY_CIV_SPAIN_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Reino de Espana' WHERE Tag = 'TXT_KEY_CIV_SPAIN_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Sverige' WHERE Tag = 'TXT_KEY_CIV_SWEDEN_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Konungariket Sverige' WHERE Tag = 'TXT_KEY_CIV_SWEDEN_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'Venesia' WHERE Tag = 'TXT_KEY_CIV_VENICE_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'Republica de Venesia' WHERE Tag = 'TXT_KEY_CIV_VENICE_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
		UPDATE Language_en_US SET Text = 'KwaZulu' WHERE Tag = 'TXT_KEY_CIV_ZULU_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
			UPDATE Language_en_US SET Text = 'KwaZulu' WHERE Tag = 'TXT_KEY_CIV_ZULU_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1);
				
			-- Polinesia
			-- renaming to Polenisia
			UPDATE Language_en_US SET Text = 'Polenisia' WHERE Tag = 'TXT_KEY_CIV_POLYNESIA_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNHAW' AND Value=1);
				UPDATE Language_en_US SET Text = 'Polenisia' WHERE Tag = 'TXT_KEY_CIV_POLYNESIA_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNHAW' AND Value=1);
				-- renaming to Hawai'i
				UPDATE Language_en_US SET Text = 'Hawai''i' WHERE Tag = 'TXT_KEY_CIV_POLYNESIA_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNHAW' AND Value=2);
					UPDATE Language_en_US SET Text = 'Aupuni Mo''i o Hawai''i' WHERE Tag = 'TXT_KEY_CIV_POLYNESIA_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNHAW' AND Value=2);
			
			-- Greece
			UPDATE Language_en_US SET Text = 'Ellas' WHERE Tag = 'TXT_KEY_CIV_GREECE_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNMAC' AND Value=0);
				UPDATE Language_en_US SET Text = 'Ellas' WHERE Tag = 'TXT_KEY_CIV_GREECE_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNMAC' AND Value=0);
					-- renaming to Macedonia
					UPDATE Language_en_US SET Text = 'Macedonia' WHERE Tag = 'TXT_KEY_CIV_GREECE_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNMAC' AND Value=1);
						UPDATE Language_en_US SET Text = 'Macedonia' WHERE Tag = 'TXT_KEY_CIV_GREECE_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNMAC' AND Value=1);
					-- renaming to Makedonia
					UPDATE Language_en_US SET Text = 'Makedonia' WHERE Tag = 'TXT_KEY_CIV_GREECE_SHORT_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNMAC' AND Value=2);
						UPDATE Language_en_US SET Text = 'Makedonia' WHERE Tag = 'TXT_KEY_CIV_GREECE_DESC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIV' AND Value=1) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNMAC' AND Value=2);
--==============================================================================================================================================================================================================================================================================================--
--==============================================================================================================================================================================================================================================================================================--
-- Civilization Leader Names
	-- Endoetnonyms
		-- VP
		UPDATE Language_en_US SET Text = 'Kazimierz III Wielki' WHERE Tag = 'TXT_KEY_LEADER_CASIMIR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNLEA' AND Value=1);
--==============================================================================================================================================================================================================================================================================================--
--==============================================================================================================================================================================================================================================================================================--
-- City Names
	-- Poland
		DELETE FROM Civilization_CityNames WHERE CivilizationType = 'CIVILIZATION_POLAND' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_1', 'Krakow', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_2', 'Warszawa', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_3', 'Lwow', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_4', 'Poznan', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_5', 'Leczyca', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_6', 'Plock', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_7', 'Gniezno', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_8', 'Halicz', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_9', 'Sieradz', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_10', 'Kalisz', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_11', 'Przemysl', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_12', 'Bydgoszcz', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_13', 'Lublin', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_14', 'Sandomierz', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_15', 'Biecz', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_16', 'Elblag', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_17', 'Kijow', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_18', 'Czestochowa', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_19', 'Torun', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_20', 'Sejny', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_21', 'Zamosc', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_22', 'Gdansk', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_23', 'Kamieniec Podolski', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_24', 'Wilno', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_25', 'Kazimierz', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_26', 'Braniewo', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_27', 'Nowy Sacz', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_28', 'Troki', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_29', 'Wroclaw', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_30', 'Lodz', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_31', 'Katowice', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_32', 'Szczecin', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_33', 'Gdynia', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Language_en_US SELECT 'TXT_KEY_POLAND_CITY_34', 'Gliwice', null, null WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_1' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_2' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_3' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_4' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_5' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_6' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_7' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_8' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_9' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_10' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_11' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_12' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_13' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_14' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_15' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_16' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_17' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_18' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_19' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_20' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_21' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_22' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_23' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_24' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_25' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_26' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_27' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_28' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_29' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_30' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_31' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_32' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_33' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
		INSERT INTO Civilization_CityNames SELECT 'CIVILIZATION_POLAND', 'TXT_KEY_POLAND_CITY_34' WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNCIT' AND Value=1);
--==============================================================================================================================================================================================================================================================================================--
--==============================================================================================================================================================================================================================================================================================--
-- Random City Names (from UI - Random City Names mod by @whoward69)
	-- create a temp city name table keeping all the Capital City names (first entry for each civ - hence the order by and group by clauses)
	CREATE TABLE IF NOT EXISTS Civilization_CityNames_Temp AS
	SELECT * 
	FROM (SELECT * FROM Civilization_CityNames ORDER BY rowid DESC) 
	GROUP BY CivilizationType;

	-- copy the remaining cities to the temp table in a random order  
	INSERT INTO Civilization_CityNames_Temp
	SELECT DISTINCT *
	FROM Civilization_CityNames
	WHERE
		NOT EXISTS (SELECT * FROM Civilization_CityNames_Temp WHERE CityName = Civilization_CityNames.CityName)
		AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNRAN' AND Value=1)
	ORDER BY RANDOM();

	-- copy everything back from the temp table, keeping the same order, and then tidy up after ourselves
	DELETE FROM Civilization_CityNames WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNRAN' AND Value=1);
	
	INSERT INTO Civilization_CityNames 
	SELECT *
	FROM Civilization_CityNames_Temp
	WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='ACNRAN' AND Value=1)
	ORDER BY rowid ASC;
	
	DROP TABLE IF EXISTS Civilization_CityNames_Temp;
--==============================================================================================================================================================================================================================================================================================--
--==============================================================================================================================================================================================================================================================================================--